export enum IconEnum {
  Dashboard = 'dashboard',
  InvertColours = 'invert_colors',
  Settings = 'settings',
  Newspaper = 'newspaper',
  Visibility = 'visibility',
  Twitter = 'twitter',
  TrendingUp = 'trending-up',
  PermMedia = 'perm-media',
  Clear = 'clear',
  Done = 'done',
  Edit = 'edit',
  Person = 'person',
  Subject = 'subject',
  WatchLater = 'watch-later',
  CaretDown = 'caret-down',
  Bar = 'bar',
}
